version: '3'

services:
  manim-api:
    image: wstcpyt/manim-docker-mcp:latest
    ports:
      - "8000:8000"
    volumes:
      - ./output:/manim/output
      - ./uploads:/manim/uploads
      - ./temp:/manim/temp
    restart: unless-stopped
  manim:
    image: wstcpyt/manim-docker-mcp:latest
    volumes:
      - ./animations:/manim/animations
      - ./media:/manim/media
    working_dir: /manim
    # Example command to render a scene
    # command: -pql animations/example.py ExampleScene 